# Generated by Django 2.2.13 on 2020-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20200705_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'meal', 'verbose_name_plural': 'meals'},
        ),
        migrations.AddField(
            model_name='meals',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
